### ISSUE TITLE
Full Width on Yahoo iOS and Android

### ISSUE THREAD

**Issue by braddunzer** [ThemeMountain/pine#19]
Just started playing with PINE and finding some rendering issues on Yahoo App on iOS and Android.

Appears the body of the email is not going full width.
![yahoo-app-ios](https://user-images.githubusercontent.com/30672869/34363836-5d76b078-ea34-11e7-8b22-f271943af0d4.jpg)

All I did was add one of your standard components into the area that says start rows here.

**Comment by braddunzer** [comment]
Update on this. My bad. It was the injected footer I was using was not fluid.

But I did find another issue. The set padding on feature-columns.html file was causing an issue in Yahoo App. The Class px-sm-2 that was applied to the <TD> as well as the set style of padding:30px was causing the Container to be 30px narrower than the columns. I wrapped the contents of each <TD> in a DIV and applied the class and the inline style padding on that DIV. Seems to have done the trick

**Comment by cossssmin** [comment]
Hi Brad, sorry for the late reply, holidays and all that... :)

Indeed, that is an issue with Yahoo! on mobile and padding on table cells. I've ran a test where only the first cell would have padding set for mobile, and no matter how it's set (inline CSS, or `cellpadding=""` attribute), Yahoo! always fails miserably, allowing content to overflow outside the columns/container:

![image](https://user-images.githubusercontent.com/1656595/34608346-9287bfb6-f220-11e7-8bed-db666d3984d1.png)

As you can see, the purple column, having no padding set, doesn't have content overflowing.

Unfortunately, using a `<div>` with padding on it won't work for Outlook, so a better solution is to wrap the contents with another table, setting padding on its cell instead:

```html
<table align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td>
      <table cellpadding="0" cellspacing="0" role="presentation" width="100%">
        <tr>
          <td class="col" width="290">
            <table cellpadding="30" cellspacing="0" role="presentation" width="100%">
              <tr>
                <td align="center">
            	  <img src="https://i.imgur.com/XqzhK67.png" width="36" alt="Download" style="max-width: 36px; width: 100%;" />
            	  <h3>Download our app</h3>
            	  <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
              	</td>
              </tr>
            </table>
          </td>
          <td class="col" align="center" bgcolor="#7E57C2" width="290">
            <table cellpadding="30" cellspacing="0" role="presentation" width="100%">
              <tr>
                <td align="center">
            	  <img src="https://i.imgur.com/BuBHL3w.png" width="36" alt="Download" style="max-width: 36px; width: 100%;" />
            	  <h3 style="color: #FFFFFF;">Take control</h3>
            	  <div style="color: #FFFFFF;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
```

Tested this in the Yahoo! mobile app, and looks to be working fine:

![image](https://user-images.githubusercontent.com/1656595/34608647-0480a4a6-f222-11e7-8e60-75f4205ffcb7.png)

However, I'm not sure I want to add that to the framework, just because of Yahoo!'s stupid handling of the box model. That is very likely to change in the short term plus, the content inside those columns shouldn't be the framework's concern - people may or may not need that padding, and I think it's easier to turn it off by just removing a class or inline CSS, instead of having to remove lots of markup.

I'll think about it some more, maybe I'm wrong...
