### ISSUE TITLE
Info on setup

### ISSUE THREAD

**Issue by wolfhumble** [ThemeMountain/pine#4]
Hi,

Saw your framework via: 
https://litmus.com/community/discussions/5407-what-is-your-email-framework-of-choice#comment-10405 and it is looking good, thanks! 👍

I have been writing quite a few HTML mails before, but have not studied what the "state of the art of HTML e-mails" is these days.

Looking through your excellent documentation on: http://pine.thememountain.com/
I was just wondering about a few things:
1) How would the typical HTML header look like when using the Pine framework?
I see that e.g. the following is used in: layout/default.html — but I am not sure if that is the way is meant to be set up in all cases?

```html
<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!--[if mso]>
    <xml>
      <o:OfficeDocumentSettings>
        <o:AllowPNG/>
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->

    . . . .
```
2) Another thing I was wondering about is the CSS:
I guess all CSS will have to be inserted INLINE in the mail itself?

3) Images
Does all images have to be linked to remotely, or is it possible to include them INLINE in some cases? (I am not sure how different mail clients treat inline images these days?)

Again: Thanks for a great framework and documentation — I can see you have put a lot of time into this! :-)

Wolf

**Comment by wolfhumble** [comment]
4) One more thing, the file:  layout/default.html 
has the following comment: 
```html
<!-- ADD ROWS HERE -->
```
I guess that is where you paste in the examples found on http://pine.thememountain.com — i.e. the full TABLES?

Thanks!

Wolf

**Comment by cossssmin** [comment]
Hi Wolf,

Thanks for the kind words :)

1. The header you can see in `layout/default.html`, just as you pointed out - [here's the code, highlighted](https://github.com/ThemeMountain/tm-pine/blob/master/layout/default.html#L4-L175). 
It's just the basics to get you started + a few small extras to ensure compatibility. Simply start from that layout and, when done, I recommend you remove what you don't need. For example, if you don't need Outlook background image support, you can remove the `xmlns:v="urn:schemas-microsoft-com:vml"` attribute on the `<body>` tag. Not using menus? You can remove the CSS related to it. Not using all the `mobile-x` classes for responsive? Remove the unused ones after you've completed your layout, in order to reduce the file size. Of course, you can add whatever you need that you feel is missing, it's just a base to get you started.

2. The CSS you see in the `<style>` tag does not need to be inlined. Most of it is for mobile devices (wrapped in that `@media` query), so for responsive you just use those classes on HTML elements, as the docs indicate. The grid itself already has inlined CSS, so you can just copy-paste grid elements. Of course, if you add content that is not already provided by Pine, you will need to add CSS - but just take a look at how we do it, it's pretty simple.

3. The images need to be hosted and linked to with absolute URLs, yes. Never inline. When sending emails, you should use an ESP (i.e. MailChimp, Campaign Monitor, etc.) - these host your images for you and offer tons more features. Don't send campaigns via your Outlook or Gmail account.

4. Yes, you simply replace that comment with grid rows from the `grid/` folder, stacked one after the other. I think maybe I should create some simple example layouts, to be shipped with the framework - do you think that would help?

Thanks again for your comment, if you have ideas that you think could help improve Pine, do tell :)

**Comment by wolfhumble** [comment]
Thanks for your feedback!

1) In https://templates.mailchimp.com/development/html/ I was just seeing that they were using the following:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
```
So I was wondering if any e-mail readers would have any problem using:
```html
<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
```
But from your testing that does not seem to be the case?

2) I actually wrote INLINE when I meant "Internal style sheet" compared to external style sheets, but I get your point, thanks! And I guess mail readers still don't support external style sheets, right?

3) Just as I thought then, thanks.

4) Since HTML mails are a little finicky it might be nice to have 1-2 examples as a starting point.
But I must admit that when I spent some time looking at the examples and the documentation, 99% of it made sense (I actually just saw the layout/default.html file as I was typing up my questions, and that made things much clearer. Maybe just create a file called example.html or something on the root of the directory to make things even clearer?)

5) I see that layout/default.html includes the following (removed a couple of empty rows):
```html
<body style="box-sizing: border-box; margin: 0; padding: 0; width: 100%;">
    <table class="wrapper" align="center" bgcolor="#EEEEEE" style="border-spacing: 0; margin: 0 auto; width: 100%;">
      <tr>
        <td style="padding: 0;">
        <!-- ADD ROWS HERE -->
        </td>
      </tr>
    </table>
```

And the example code on e.g.  http://pine.thememountain.com/components/testimonial.html starts with:
```html
<table class="wrapper" align="center" bgcolor="#EEEEEE" style="border-spacing: 0; margin: 0 auto; width: 100%;">
  <tr>
    <td style="padding: 0;">
      <table class="row" align="center" bgcolor="#FFFFFF" style="border-spacing: 0; margin: 0 auto;">
```

Maybe just change layout/default.html to . . . :
```html
<body style="box-sizing: border-box; margin: 0; padding: 0; width: 100%;">
   <!-- ADD ROWS HERE -->
```

. . . since you will get the first: ```"<table><tr><td>"``` twice if you copy and paste from the examples:
```html
<table class="wrapper" align="center" bgcolor="#EEEEEE" style="border-spacing: 0; margin: 0 auto; width: 100%;">
  <tr>
    <td style="padding: 0;">
    <!-- ADD ROWS HERE -->
    <table class="wrapper" align="center" bgcolor="#EEEEEE" style="border-spacing: 0; margin: 0 auto; width: 100%;">
    <tr>
      <td style="padding: 0;">
        <table class="row" align="center" bgcolor="#FFFFFF" style="border-spacing: 0; margin: 0 auto;">
    
```

But maybe you had another thought behind that?

Thanks again for your feedback and for your hard work! :-)

Wolfhumble

**Comment by cossssmin** [comment]
Heya,

1. We're using the HTML5 doctype, as opposed to the Transitional doctype you've seen in the MailChimp templates. Of course, we've tested before implementing and it's working fine everywhere. As long as it works consistently, the less code, the better.

2. Oh, sorry, got confused. Just to clear things up, 'inline CSS' is used when talking about CSS in a `style=""` attribute, directly on HTML elements. CSS in a `<style>` tag inside the head/body of the HTML, is reffered to as 'embedded CSS'. And you're right, email clients do not support external stylesheets.

4. You're right, will think of improving the base/examples, to make the learning curve easier :)

5. This is something I need to improve in the docs&deliverables:

Pine uses two layout techniques, as you can see in the [grid wrappers docs](https://thememountain.github.io/pine/components/grid.html#wrappers). 

Wrapper tables are used to offer the possibility of adding a background colour to the body of the email , that is different from the row's bg colour. This way, you can create a boxed layout, and even alternate colours (see [individual wrapper backgrounds](https://thememountain.github.io/pine/components/grid.html#individual-wrappers) for docs, and [this fiddle](https://jsfiddle.net/0strw6m7/) for a better visual example). Of course, you can go the route you suggested and only stack row tables directly in the `<body>`, thus achieving a full width layout effect.

The base `layout.html` that is provided at this time suggests creating a boxed layout, with all rows stacked inside a single wrapper table (so, just a single bg colour for the "body"). 

I agree this might be a bit confusing and that it doesn't offer starting points for other approaches, so we'll soon be providing better examples, for each use case. If this doesn't make sense, it will as soon as you see them ;)

Thanks,
Cosmin
